---
title: "Assignment 2"
author:
  Christopher Bovolos (st.number 13979582)
date: "22 November 2021"
output:
  pdf_document: default
  word_document: default
fontsize: 11pt
highlight: tango
---
```{r, echo=FALSE,message=FALSE}
library(fpp3)
library(repr)
library(IRdisplay)
library(evaluate)
library(crayon)
library(pbdZMQ)
library(devtools)
library(uuid)
library(digest)
library(ggplot2)
library(gtable)
library(grid)
library(prophet)
# library(forecast)
```

## \textcolor{blue}{Exercises}

```{r}
#Round function we will use later or not, ignore for now
round2 = function(x, n) {
  posneg = sign(x)
  z = abs(x)*10^n
  z = z + 0.5 + sqrt(.Machine$double.eps)
  z = trunc(z)
  z = z/10^n
  z*posneg
}

```

```{r, message=FALSE,echo = FALSE}
train <- read.csv("sales_train_validation_afcs2021.csv")
test <- read.csv("test.csv")
calendar <- read.csv("calendar.csv")


#Preprocess the data
train = as_tibble(cbind(nms = names(train), t(train)))
test = as_tibble(cbind(nms = names(test), t(test)))



test = test %>%  slice(2 : n()) %>% tibble::rowid_to_column("Day") %>% 
  select(-nms)%>%  mutate(Day = Day +1913) %>% 
  as_tsibble(index = Day) %>% mutate_each(funs(as.numeric), starts_with("V")) 


train = train %>%  slice(2 : n()) %>% tibble::rowid_to_column("Day") %>% 
  select(-nms)%>% 
  as_tsibble(index = Day) %>% mutate_each(funs(as.numeric), starts_with("V"))

#Preprocess the whole calendar
#Make character variables to integers
#Throw away garbage and keep the good stuff
calendar = calendar %>%  mutate(Event = case_when(
    event_type_1 == "Sporting" ~ 1,
    event_type_1 == "Cultural" ~ 2,
    event_type_1 == "National" ~ 3,
    event_type_1 == "Religious" ~ 4,
    TRUE ~ 0
  ),Day_type = case_when(
    weekday == "Sunday" ~ 0,
    TRUE~ 1
  )) 

calendarTest = calendar %>% slice(n()-27:0)%>% tibble::rowid_to_column("Day") %>%  mutate(Day = Day +1913)
calendar = calendar %>% slice(0 : 27-n())
calendarTrain = calendar %>% slice(0 : 27-n()) %>% tibble::rowid_to_column("Day") 

#Merge sets test,train and whole with their calendars
test =as_tsibble(merge(test, calendarTest, by.x = "Day", by.y= "Day"), index= "Day") 
test  = rename(test, Date = date)
test = test %>% mutate(Date = as.Date(Date, format = "%m/%d/%Y"))

train =as_tsibble(merge(train, calendarTrain, by.x = "Day", by.y= "Day"), index= "Day") 
train  = rename(train, Date = date)
train = train %>% mutate(Date = as.Date(Date, format = "%m/%d/%Y"))

#Bind test and train to create full set
whole = bind_rows(train,test)
```
Actual code part and testing

```{r}
whole
```
```{r}
train1 = train %>% select(V2,Date,month,Event,year)

test1 = test %>% select(V2,Date,month,Event,year)

whole1 = whole %>% select(V2,Date,month,Event,year)
          
fit1 = train %>% model(Seasonal_naive = SNAIVE(V2))

report(fit1)
forecast(fit1,test1) %>% accuracy(whole1)

```

```{r}
#Tests for the first day and second day. For every series we select we must merge them with the calendarTrain
train1 = train %>% select(V2,Date,month,Event,year)

test1 = test %>% select(V2,Date,month,Event,year)

whole1 = whole %>% select(V2,Date,month,Event,year)
          
fit1 = train1 %>% model("arima" =ARIMA(V2~ Day + month +Event  + year + 1  +pdq(2,0,4)))

report(fit1)
forecast(fit1,test1) %>% accuracy(whole1)
```

```{r, warning=FALSE}
#Loop through time series for Arima

df_rmse_arima =data.frame()

#Loop in all columns
for(i in 2:ncol(whole)){

#Loop only in first 200 columns
# for(i in 2:200){
  print(i)
  
  #create column name
  V_value <- paste("V", i, sep = "")
  
  train1 = train %>% select(V_value,Date,month,Event,year)
  test1 = test %>% select(V_value,Date,month,Event,year)
  whole11 = whole %>% select(V_value,Date,month,Event,year)
  
  #select the column of the train set for the fit of the model
  a <-assign(V_value, train1[1])
  
  fit111 = train1 %>% model("arima" =ARIMA(a ~ Day + month +Event  + year + 1  +pdq(2,0,4)))
  
  fore1  <- forecast(fit111,test1)
  
  #drop the column with the same name but wrong data
  fore1_cleaned <- fore1[-c(5)]
  #rename column so it would be the same for the accuracy function
  names(fore1_cleaned)[3] <- V_value
  #convert to fable fo the accuracy function
  fbl <- as_fable(fore1_cleaned, response = V_value, distribution =V_value)
  
  current_accuracy <- accuracy(fbl,whole11)
  
  new_df_rmse_arima<-data.frame(V_value,current_accuracy[4])
  
  df_rmse_arima=rbind(df_rmse_arima, new_df_rmse_arima)
}
```

```{r}
#remove NaNs
df_rmse_arima[is.na(df_rmse_arima)] <- 1

df_rmse_arima
unique(df_rmse_arima$RMSE)
mean(unique(df_rmse_arima$RMSE))
```

```{r}
#Place to try more advanced methods(Prophet,Fourrier,NeuralNet)

#This is seasonal decomposition with seasonal adjusted data, 0.79 RMSE
#Best Results so far
# 
# try = ts(train1$V2)

try = as_tsibble(try) %>% rename( V2 = value)
dcmp =  decomposition_model(
  STL(V2 ~ season(period = 7)  , robust = TRUE),
  ETS(season_adjust))



fit = try %>% model(dcmp)
fc=forecast(fit,test1)
fc %>%accuracy(whole1)
```


```{r}
#Fourier methods are here, cant make them work
try = train %>% select(V2,Date,month,Event,year,Day_type)
whole1 = whole %>% select(V2,Date,month,Event,year,Day_type)
test1 = test %>% select(V2,Date,month,Event,year,Day_type)


try  =as_tsibble(try, index= "Date") %>%  select(-Day)
whole1 = as_tsibble(whole1, index= "Date") %>%  select(-Day)
test1 =  as_tsibble(test1, index= "Date") %>%  select(-Day)
FIT =try %>% model(
                   try =ARIMA( V2 ~ Date +month +Event  + 1 + PDQ(0,0,0) +pdq(3,0,2) )
                  )

fc= forecast(FIT, test1)
accuracy(fc, whole1)
```

```{r}
try = train %>% select(V2,Date,month,Event,year,Day_type)
whole1 = whole %>% select(V2,Date,month,Event,year,Day_type)
test1 = test %>% select(V2,Date,month,Event,year,Day_type)
try  =as_tsibble(try, index= "Date") %>%  select(-Day)
whole1 = as_tsibble(whole1, index= "Date") %>%  select(-Day)
test1 =  as_tsibble(test1, index= "Date") %>%  select(-Day)
```


```{r}
FIT =try %>% model(prophet = prophet(V2 ~Date +month +Event+ season("day", type = "multiplicative")))
report(FIT)
fc= forecast(FIT, test1)
accuracy(fc, whole1)
```

```{r}
dcmp =  try %>% model(
  STL(V2 ~ season(period = 7)  , robust = TRUE),
  ETS(season_adjust))

fc= forecast(dcmp, test1)
accuracy(fc, whole1)
```

```{r, warning=FALSE}
#Loop through time series for prophet

df_rmse_prophet =data.frame()

#Loop in all columns
for(i in 2:824){
  print(i)
  V_value <- paste("V", i, sep = "")
  
  try = train %>% select(V_value,Date,month,Event,year,Day_type)
  whole1 = whole %>% select(V_value,Date,month,Event,year,Day_type)
  test1 = test %>% select(V_value,Date,month,Event,year,Day_type)
  try  =as_tsibble(try, index= "Date") %>%  select(-Day)
  whole1 = as_tsibble(whole1, index= "Date") %>%  select(-Day)
  test1 =  as_tsibble(test1, index= "Date") %>%  select(-Day)

  a <- as.numeric(unlist(try[1]))
  FIT =try %>% model(prophet = prophet(a ~Date +month +Event+ season("day", type = "multiplicative")))
  
  fore1  <- forecast(FIT,test1)
  fore1_cleaned <- fore1[-c(5)]
  names(fore1_cleaned)[3] <- V_value
  fbl <- as_fable(fore1_cleaned, response = V_value, distribution =V_value)
  current_accuracy <- accuracy(fbl,whole1)
  new_df_rmse_prophet<-data.frame(V_value,current_accuracy[4])
  df_rmse_prophet=rbind(df_rmse_prophet, new_df_rmse_prophet)
}

```
```{r}
# testttt =  as_tsibble(try[1], index= "V2")
df_rmse_prophet
# as.numeric(unlist(try[1]))
```

```{r}
#remove NaNs
df_rmse_prophet[is.na(df_rmse_prophet)] <- 1

df_rmse_prophet
unique(df_rmse_prophet$RMSE)
mean(unique(df_rmse_prophet$RMSE))
```


```{r}
library(fable.prophet)

train1 %>% 
  autoplot(V2)

train1 = train %>% select(V2,Date,month,Event,year)

test1 = test %>% select(V2,Date,month,Event,year)

whole1 = whole %>% select(V2,Date,month,Event,year)

fit2 <- train %>% model(prophet = prophet(V2 ~ season("month", type = "multiplicative")))
report(fit2)
fc <- fit2 %>% forecast(h = 2)
forecast(fit2,test1) %>% accuracy(whole1)

```
```{r}

train <- read.csv("sales_train_validation_afcs2021.csv")
test <- read.csv("test.csv")
calendar <- read.csv("calendar.csv")
submissions = read.csv("sample_submission_afcs2021.csv")


#Preprocess the data
train = as_tibble(cbind(nms = names(train), t(train)))
test = as_tibble(cbind(nms = names(test), t(test)))
submissions = as_tibble(cbind(nms = names(submissions), t(submissions)))


test = test %>%  slice(2 : n()) %>% tibble::rowid_to_column("Day") %>% 
  select(-nms)%>%  mutate(Day = Day +1913) %>% 
  as_tsibble(index = Day) %>% mutate_each(funs(as.numeric), starts_with("V")) 


train = train %>%  slice(2 : n()) %>% tibble::rowid_to_column("Day") %>% 
  select(-nms)%>% 
  as_tsibble(index = Day) %>% mutate_each(funs(as.numeric), starts_with("V"))

submissions = submissions %>%  slice(2 : n()) %>% tibble::rowid_to_column("Day") %>% 
  select(-nms)%>% mutate(Day = Day +1941) %>% 
  as_tsibble(index = Day) %>% mutate_each(funs(as.numeric), starts_with("V"))


#Preprocess the whole calendar
#Make character variables to integers
#Throw away garbage and keep the good stuff
calendar = calendar %>%  mutate(Event = case_when(
    event_type_1 == "Sporting" ~ 1,
    event_type_1 == "Cultural" ~ 2,
    event_type_1 == "National" ~ 3,
    event_type_1 == "Religious" ~ 4,
    TRUE ~ 0
  ),Day_type = case_when(
    weekday == "Sunday" ~ 1,
    weekday == "Saturday" ~ 7,
    weekday == "Monday" ~ 2,
    weekday == "Tuesday" ~ 3,
    weekday == "Wednesday" ~ 4,
    weekday == "Thursday" ~ 5,
    weekday == "Friday" ~ 6,
    TRUE~ 1
  )) 

calendarTest = calendar %>% slice(n()-27:0)%>% tibble::rowid_to_column("Day") %>%  mutate(Day = Day +1913)
calendar = calendar %>% slice(0 : 27-n())
calendarTrain = calendar %>% slice(0 : 27-n()) %>% tibble::rowid_to_column("Day") 

#Preprocess submissions to match our ARIMA params
submissions$Day_type <- rep(c(2,3,4,5,6,7,1), times = 4)
submissions$month <- rep(c(6,6,6,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7))
submissions$year <- rep(2016, times = 28)
submissions$Event <- rep(c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0))
submissions$Day <- seq(1942,1969)
submissions$Date = seq(as.Date("2016/06/20"), as.Date("2016/07/17"), "days")
submissions = as_tsibble(submissions,index= "Day")

#Merge sets test,train and whole with their calendars
test =as_tsibble(merge(test, calendarTest, by.x = "Day", by.y= "Day"), index= "Day") 
test  = rename(test, Date = date)
test = test %>% mutate(Date = as.Date(Date, format = "%m/%d/%Y"))

train =as_tsibble(merge(train, calendarTrain, by.x = "Day", by.y= "Day"), index= "Day") 
train  = rename(train, Date = date)
train = train %>% mutate(Date = as.Date(Date, format = "%m/%d/%Y"))

#Bind test and train to create full set
whole = bind_rows(train,test)

```

```{r, warning=FALSE}
#Loop through time series for Arima

df_rmse_arima =data.frame()

#Loop in all columns
# for(i in 2:ncol(whole)){

#Loop only in first 200 columns
for(i in 2:824){
  #create column name
  V_value <- paste("V", i, sep = "")
  print(i)
  try = train %>% select(V_value,Date,month,Event,year,Day_type)
  whole1 = whole %>% select(V_value,Date,month,Event,year,Day_type)
  test1 = test %>% select(V_value,Date,month,Event,year,Day_type)
  try  =as_tsibble(try, index= "Date") %>%  select(-Day)
  whole1 = as_tsibble(whole1, index= "Date") %>%  select(-Day)
  test1 =  as_tsibble(test1, index= "Date") %>%  select(-Day)
  submissions1 = submissions  %>% select(V_value,Date,month,Event,year,Day_type)
  submissions1 =  as_tsibble(submissions1, index= "Date") %>%  select(-Day)
  
  
  a <- as.numeric(unlist(try[1]))
  FIT =try %>% model(prophet = prophet(a ~Date +month +Event+ season("day", type = "multiplicative")))
  fore1  = forecast(FIT,submissions1)
  
  
  for(j in 1:28){
    mean = fore1[j,".mean"]
    submissions[j,i] = mean
  }
  
}
submissions
subdf = as.data.frame(submissions)
columnsToDrop = c("Day","Event","month", "year", "Day_type", "Date")
subdf = subdf[,!(names(subdf) %in% columnsToDrop)]
submissionsStore = subdf
accumulator = 0
subdf
for(i in 1 : 823){

  if((i == 737 )| (i== 52) |(i== 698) |(i== 726)  ){
    accumulator = accumulator + 1
  }
  value =accumulator + i
  if(i<10){
    names(subdf)[i] = paste("FOODS_3_00",value,"_TX_3_validation", sep = "")
  }
  if(i<=99){
    names(subdf)[i] = paste("FOODS_3_0",value,"_TX_3_validation", sep = "")
  }
  if( i >99){
    names(subdf)[i] = paste("FOODS_3_",value,"_TX_3_validation", sep = "")
  }
}
subdf[is.na(subdf)] <- 0
transp = as_tibble(cbind(nms = names(subdf), t(subdf)))
transp

for(j in 2 : 29){

  
  names(transp)[j] = paste("F",j-1, sep = "")
 
}

transp = as.data.frame(transp)
names(transp)[1] = "id"
transp =transp %>% mutate_each(funs(as.numeric), starts_with("F"))
write.csv(transp,"submission1.csv", row.names = FALSE)

# 
# 
# transp = as_tibble(cbind(nms = names(submissionsCleared), t(submissionsCleared)))
# transp
```


```{r}
# ###############################################
train <- read.csv("sales_train_validation_afcs2021.csv")
test <- read.csv("test.csv")
calendar <- read.csv("calendar.csv")
submissions = read.csv("sample_submission_afcs2021.csv")


#Preprocess the data
train = as_tibble(cbind(nms = names(train), t(train)))
test = as_tibble(cbind(nms = names(test), t(test)))
submissions = as_tibble(cbind(nms = names(submissions), t(submissions)))


test = test %>%  slice(2 : n()) %>% tibble::rowid_to_column("Day") %>% 
  select(-nms)%>%  mutate(Day = Day +1913) %>% 
  as_tsibble(index = Day) %>% mutate_each(funs(as.numeric), starts_with("V")) 


train = train %>%  slice(2 : n()) %>% tibble::rowid_to_column("Day") %>% 
  select(-nms)%>% 
  as_tsibble(index = Day) %>% mutate_each(funs(as.numeric), starts_with("V"))

submissions = submissions %>%  slice(2 : n()) %>% tibble::rowid_to_column("Day") %>% 
  select(-nms)%>% mutate(Day = Day +1941) %>% 
  as_tsibble(index = Day) %>% mutate_each(funs(as.numeric), starts_with("V"))


#Preprocess the whole calendar
#Make character variables to integers
#Throw away garbage and keep the good stuff
calendar = calendar %>%  mutate(Event = case_when(
    event_type_1 == "Sporting" ~ 1,
    event_type_1 == "Cultural" ~ 2,
    event_type_1 == "National" ~ 3,
    event_type_1 == "Religious" ~ 4,
    TRUE ~ 0
  ),Day_type = case_when(
    weekday == "Sunday" ~ 1,
    weekday == "Saturday" ~ 7,
    weekday == "Monday" ~ 2,
    weekday == "Tuesday" ~ 3,
    weekday == "Wednesday" ~ 4,
    weekday == "Thursday" ~ 5,
    weekday == "Friday" ~ 6,
    TRUE~ 1
  )) 

calendarTest = calendar %>% slice(n()-27:0)%>% tibble::rowid_to_column("Day") %>%  mutate(Day = Day +1913)
calendar = calendar %>% slice(0 : 27-n())
calendarTrain = calendar %>% slice(0 : 27-n()) %>% tibble::rowid_to_column("Day") 

#Preprocess submissions to match our ARIMA params
submissions$Day_type <- rep(c(2,3,4,5,6,7,1), times = 4)
submissions$month <- rep(c(6,6,6,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7))
submissions$year <- rep(2016, times = 28)
submissions$Event <- rep(c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0))
submissions$Day <- seq(1942,1969)
submissions$Date = seq(as.Date("2016/06/20"), as.Date("2016/07/17"), "days")
submissions = as_tsibble(submissions,index= "Day")

#Merge sets test,train and whole with their calendars
test =as_tsibble(merge(test, calendarTest, by.x = "Day", by.y= "Day"), index= "Day") 
test  = rename(test, Date = date)
test = test %>% mutate(Date = as.Date(Date, format = "%m/%d/%Y"))

train =as_tsibble(merge(train, calendarTrain, by.x = "Day", by.y= "Day"), index= "Day") 
train  = rename(train, Date = date)
train = train %>% mutate(Date = as.Date(Date, format = "%m/%d/%Y"))

#Bind test and train to create full set
whole = bind_rows(train,test)
```

```{r, warning=FALSE}
#Loop through time series for Arima

df_rmse_arima =data.frame()

#Loop in all columns
# for(i in 2:ncol(whole)){

#Loop only in first 200 columns
for(i in 2:824){
  #create column name
  V_value <- paste("V", i, sep = "")
  
  train1 = train %>% select(V_value,Date,month,Event,year,Day_type)
  test1 = test %>% select(V_value,Date,month,Event,year,Day_type)
  submissions1 = submissions  %>% select(V_value,Date,month,Event,year,Day_type)
  whole11 = whole %>% select(V_value,Date,month,Event,year,Day_type)
  #select the column of the train set for the fit of the model
  a <-assign(V_value, train1[1])
  
  fit111 = train1 %>% model("arima" =ARIMA(a ~ Day + month +Event  + year + Day_type+1 ))
  # fit111 = whole11 %>% model(dcmp) 
  
  fore1  = forecast(fit111,submissions1)
  
  
  for(j in 1:28){
    mean = fore1[j,".mean"]
    submissions[j,i] = mean
  }
  
}
submissions
subdf = as.data.frame(submissions)
columnsToDrop = c("Day","Event","month", "year", "Day_type", "Date")
subdf = subdf[,!(names(subdf) %in% columnsToDrop)]
submissionsStore = subdf
accumulator = 0
subdf
for(i in 1 : 823){

  if((i == 737 )| (i== 52) |(i== 698) |(i== 726)  ){
    accumulator = accumulator + 1
  }
  value =accumulator + i
  if(i<10){
    names(subdf)[i] = paste("FOODS_3_00",value,"_TX_3_validation", sep = "")
  }
  if(i<=99){
    names(subdf)[i] = paste("FOODS_3_0",value,"_TX_3_validation", sep = "")
  }
  if( i >99){
    names(subdf)[i] = paste("FOODS_3_",value,"_TX_3_validation", sep = "")
  }
}
subdf[is.na(subdf)] <- 0
transp = as_tibble(cbind(nms = names(subdf), t(subdf)))
transp

for(j in 2 : 29){

  
  names(transp)[j] = paste("F",j-1, sep = "")
 
}

transp = as.data.frame(transp)
names(transp)[1] = "id"
transp =transp %>% mutate_each(funs(as.numeric), starts_with("F"))
write.csv(transp,"submission_ARIMA .csv", row.names = FALSE)

# 
# 
# transp = as_tibble(cbind(nms = names(submissionsCleared), t(submissionsCleared)))
# transp

```

```{r}
report(fit111)
```

```{r, warning=FALSE}
#Loop through time series for Arima

df_rmse_arima =data.frame()

#Loop in all columns
# for(i in 2:ncol(whole)){

#Loop only in first 200 columns
for(i in 2:824){
  #create column name
  V_value <- paste("V", i, sep = "")
  
  train1 = train %>% select(V_value,Date,month,Event,year,Day_type)
  test1 = test %>% select(V_value,Date,month,Event,year,Day_type)
  submissions1 = submissions  %>% select(V_value,Date,month,Event,year,Day_type)
  whole11 = whole %>% select(V_value,Date,month,Event,year,Day_type)
  #select the column of the train set for the fit of the model
  a <-assign(V_value, train1[1])
  
  fit111 = train1 %>% model("arima" =ARIMA(a ~ Day + month +Event  + year + Day_type+1 ))
  # fit111 = whole11 %>% model(dcmp) 
  
  fore1  = forecast(fit111,submissions1)
  
  
  for(j in 1:28){
    mean = fore1[j,".mean"]
    submissions[j,i] = mean
  }
  
}
submissions
subdf = as.data.frame(submissions)
columnsToDrop = c("Day","Event","month", "year", "Day_type", "Date")
subdf = subdf[,!(names(subdf) %in% columnsToDrop)]
submissionsStore = subdf
accumulator = 0
subdf
for(i in 1 : 823){

  if((i == 737 )| (i== 52) |(i== 698) |(i== 726)  ){
    accumulator = accumulator + 1
  }
  value =accumulator + i
  if(i<10){
    names(subdf)[i] = paste("FOODS_3_00",value,"_TX_3_validation", sep = "")
  }
  if(i<=99){
    names(subdf)[i] = paste("FOODS_3_0",value,"_TX_3_validation", sep = "")
  }
  if( i >99){
    names(subdf)[i] = paste("FOODS_3_",value,"_TX_3_validation", sep = "")
  }
}
subdf[is.na(subdf)] <- 0
transp = as_tibble(cbind(nms = names(subdf), t(subdf)))
transp

for(j in 2 : 29){

  
  names(transp)[j] = paste("F",j-1, sep = "")
 
}

transp = as.data.frame(transp)
names(transp)[1] = "id"
transp =transp %>% mutate_each(funs(as.numeric), starts_with("F"))
write.csv(transp,"submission_ARIMA .csv", row.names = FALSE)

# 
# 
# transp = as_tibble(cbind(nms = names(submissionsCleared), t(submissionsCleared)))
# transp

```

